/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import React, { useEffect, useRef, useState } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'
import { useFrame, useThree } from "@react-three/fiber"

export default function Model({scroll, ...props}) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Extruder.glb')
  const [hovered, set] = useState()
  const { actions } = useAnimations(animations, group)

  useEffect(() => void (actions["CameraMovement01"].play().paused = true), [])

  useFrame((state) => {
    actions["CameraMovement01"].time = THREE.MathUtils.lerp(actions["CameraMovement01"].time, actions["CameraMovement01"].getClip().duration * scroll.current, 0.05) 
    console.log( ); })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene"

        onPointerOver={(e) => (e.stopPropagation(), set(e.object.name))}
        onPointerOut={(e) => (e.stopPropagation(), set(null))}
        position={[0.06, 4.04, 0.35]}
        scale={[0.25, 0.25, 0.25]}>
        <group name="Camera" position={[0.81, 8.85, 10.73]} rotation={[0.75, 0, 0]}>
          <PerspectiveCamera name="Camera_Orientation" makeDefault={true} far={1000} near={0.1} fov={22.9} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <mesh name="Bearing_End_plate" geometry={nodes.Bearing_End_plate.geometry} material={materials.Bearing} position={[0.81, 1.41, 1.5]} />
        <mesh name="Extruder_Main_-_outer_Bearing_Spacer-1" geometry={nodes['Extruder_Main_-_outer_Bearing_Spacer-1'].geometry} material={materials.Bearing} position={[0.81, 1.46, 1.41]} />
        <mesh name="Bearing_Spacer" geometry={nodes.Bearing_Spacer.geometry} material={materials.Bearing} position={[0.81, 1.46, 1.41]} />
        <mesh name="Blade_BackPlug" geometry={nodes.Blade_BackPlug.geometry} material={materials.Bearing} position={[0.81, 1.46, 1.74]} />
        <mesh name="Bearing_2" geometry={nodes.Bearing_2.geometry} material={materials.Bearing} position={[0.81, 1.46, 1.45]} />
        <mesh name="Bearing_1" geometry={nodes.Bearing_1.geometry} material={materials.Bearing} position={[0.81, 1.46, 1.48]} />
        <mesh name="Bearing_3" geometry={nodes.Bearing_3.geometry} material={materials.Bearing} position={[0.81, 1.46, 1.41]} />
        <mesh name="Bearing_4" geometry={nodes.Bearing_4.geometry} material={materials.Bearing} position={[0.81, 1.46, 1.38]} />
        <mesh name="Extruder_Main_-_hex_flange_bolt_small_iso-14003" geometry={nodes['Extruder_Main_-_hex_flange_bolt_small_iso-14003'].geometry} material={materials.Nuts_Bolts} position={[0.81, 1.46, 1.56]} />
        <mesh name="Extruder_Main_-_plain_washer_small_grade_a_iso-2" geometry={nodes['Extruder_Main_-_plain_washer_small_grade_a_iso-2'].geometry} material={materials.Nuts_Bolts} position={[0.95, 1.4, 1.17]} />
        <mesh name="Extruder_Main_-_Reducer-1_hex_bolt_gradeab_iso-17001" geometry={nodes['Extruder_Main_-_Reducer-1_hex_bolt_gradeab_iso-17001'].geometry} material={materials.Nuts_Bolts} position={[0.85, 1.43, 1.12]} />
        <mesh name="Extruder_Main_-_torque_nut_04-2_iso-3002" geometry={nodes['Extruder_Main_-_torque_nut_04-2_iso-3002'].geometry} material={materials.Nuts_Bolts} position={[0.85, 1.45, 1.12]} />
        <mesh name="Extruder_Main_-_hex_bolt_gradeab_iso-17" geometry={nodes['Extruder_Main_-_hex_bolt_gradeab_iso-17'].geometry} material={materials.Nuts_Bolts} position={[0.81, 1.38, 0.87]} />
        <mesh name="Extruder_Main_-_plain_washer_chamfered_grade_a_iso-3001" geometry={nodes['Extruder_Main_-_plain_washer_chamfered_grade_a_iso-3001'].geometry} material={materials.Nuts_Bolts} position={[0.81, 1.38, 0.87]} />
        <mesh name="Extruder_Main_-_Reducer-1_feridun_-_AGM_100-L_AYAKLI_(B3)-1_PG_" geometry={nodes['Extruder_Main_-_Reducer-1_feridun_-_AGM_100-L_AYAKLI_(B3)-1_PG_'].geometry} material={materials.Nuts_Bolts} position={[0.96, 1.57, 0.82]} />
        <mesh name="Extruder_Main_-_torque_nut_04-2_iso-3003" geometry={nodes['Extruder_Main_-_torque_nut_04-2_iso-3003'].geometry} material={materials.Nuts_Bolts} position={[0.81, 1.6, 4.13]} />
        <mesh name="Extruder_Main_-_Reducer-1_hex_bolt_gradeab_iso-17002" geometry={nodes['Extruder_Main_-_Reducer-1_hex_bolt_gradeab_iso-17002'].geometry} material={materials.Nuts_Bolts} position={[0.81, 1.6, 4.18]} />
        <mesh name="Extruder_Main_-_hex_flange_bolt_small_iso-14001" geometry={nodes['Extruder_Main_-_hex_flange_bolt_small_iso-14001'].geometry} material={materials.Nuts_Bolts} position={[0.81, 1.55, 1.49]} />
        <mesh name="Extruder_Main_-_hex_flange_bolt_small_iso-14002" geometry={nodes['Extruder_Main_-_hex_flange_bolt_small_iso-14002'].geometry} material={materials.Nuts_Bolts} position={[0.9, 1.48, 1.5]} />
        <mesh name="Extruder_Main_-_torque_nut_04-2_iso-3" geometry={nodes['Extruder_Main_-_torque_nut_04-2_iso-3'].geometry} material={materials.Nuts_Bolts} position={[0.72, 1.45, 1.5]} />
        <mesh name="Extruder_Main_-_Reducer-1_Gearbox_Casing_and_Sump-1" geometry={nodes['Extruder_Main_-_Reducer-1_Gearbox_Casing_and_Sump-1'].geometry} material={materials.Gear_Box} position={[0.84, 1.42, 1.12]} />
        <mesh name="Extruder_Main_-_Reducer-1_Gearbox_Upper_Casing-1" geometry={nodes['Extruder_Main_-_Reducer-1_Gearbox_Upper_Casing-1'].geometry} material={materials.Gear_Box} position={[0.74, 1.54, 1.12]} />
        <mesh name="Extruder_Main_-_Reducer-1_ParaGearM3with36-1" geometry={nodes['Extruder_Main_-_Reducer-1_ParaGearM3with36-1'].geometry} material={materials.Gear_Box} />
        <mesh name="Circle006" geometry={nodes.Circle006.geometry} material={materials.Gear_Box} position={[0.81, 1.46, 1.17]} />
        <mesh name="Circle007" geometry={nodes.Circle007.geometry} material={materials.Gear_Box} position={[0.81, 1.46, 1.08]} />
        <mesh name="Circle008" geometry={nodes.Circle008.geometry} material={materials.Gear_Box} position={[0.89, 1.46, 1.08]} />
        <mesh name="Extruder_Main_-_Reducer-1_ParaGearM3with18-1" geometry={nodes['Extruder_Main_-_Reducer-1_ParaGearM3with18-1'].geometry} material={materials.Gear_Box} />
        <mesh name="Extruder_Main_-_Reducer-1_Input_Shaft_Bearing_Spacer-2" geometry={nodes['Extruder_Main_-_Reducer-1_Input_Shaft_Bearing_Spacer-2'].geometry} material={materials.Gear_Box} position={[0.89, 1.46, 1.14]} />
        <mesh name="Circle005" geometry={nodes.Circle005.geometry} material={materials.Gear_Box} position={[0.89, 1.46, 1.17]} />
        <mesh name="Extruder_Main_-_Reducer-1_output_driveshaft-2" geometry={nodes['Extruder_Main_-_Reducer-1_output_driveshaft-2'].geometry} material={materials.Gear_Box} position={[0.81, 1.46, 1.21]} />
        <mesh name="Extruder_Main_-_Reducer-1_output_driveshaft-2001" geometry={nodes['Extruder_Main_-_Reducer-1_output_driveshaft-2001'].geometry} material={materials.Gear_Box} position={[0.89, 1.46, 1.02]} />
        <mesh name="Extruder_Main_-_Reducer-1_Input_Coupling-1" geometry={nodes['Extruder_Main_-_Reducer-1_Input_Coupling-1'].geometry} material={materials.Motor} position={[0.89, 1.46, 0.97]} />
        <mesh name="Extruder_Main_-_Reducer-1_feridun_-_AGM_100-L_AYAKLI_(B3)-1005" geometry={nodes['Extruder_Main_-_Reducer-1_feridun_-_AGM_100-L_AYAKLI_(B3)-1005'].geometry} material={materials.Motor} position={[0.89, 1.46, 0.99]} />
        <mesh name="Extruder_Main_-_socket_set_screw_flat_point_iso-4" geometry={nodes['Extruder_Main_-_socket_set_screw_flat_point_iso-4'].geometry} material={materials.Motor} position={[0.89, 1.45, 1.03]} />
        <mesh name="Blade_Extruder" geometry={nodes.Blade_Extruder.geometry} material={materials.Blade} position={[0.81, 1.46, 1.23]} />
        <mesh name="Blade_Extruder_body" geometry={nodes.Blade_Extruder_body.geometry} material={materials.Blade} position={[0.81, 1.47, 2.89]} />
        <mesh name="Blade_Tip" geometry={nodes.Blade_Tip.geometry} material={materials.Blade} position={[0.81, 1.46, 4.05]} />
        <mesh name="Extruder_Main_-_Extruder_Coupling-1" geometry={nodes['Extruder_Main_-_Extruder_Coupling-1'].geometry} material={materials.Blade} position={[0.81, 1.46, 1.22]} />
        <mesh name="Extruder_Main_-_socket_set_screw_flat_point_iso-2001" geometry={nodes['Extruder_Main_-_socket_set_screw_flat_point_iso-2001'].geometry} material={materials.Blade} position={[0.81, 1.46, 1.22]} />
        <mesh name="Bearing_Pressure_Plate" geometry={nodes.Bearing_Pressure_Plate.geometry} material={materials.Blade} position={[0.81, 1.46, 1.33]} />
        <mesh name="Extruder_Main_-_Blade_Extruder_Subassembly-1_Blade_Frontplug-1" geometry={nodes['Extruder_Main_-_Blade_Extruder_Subassembly-1_Blade_Frontplug-1'].geometry} material={materials.Blade} position={[0.81, 1.46, 4.05]} />
        <mesh name="Barrel_Feet" geometry={nodes.Barrel_Feet.geometry} material={materials.Barrel} position={[0.81, 1.29, 3.6]} />
        <mesh name="Extruder_Main_-_Feed_Hopper_Subassembly-2_Feed_Hopper" geometry={nodes['Extruder_Main_-_Feed_Hopper_Subassembly-2_Feed_Hopper'].geometry} material={materials.Barrel} position={[0.75, 1.8, 1.76]} />
        <mesh name="Barrel_Main" geometry={nodes.Barrel_Main.geometry} material={materials.Barrel} position={[0.81, 1.46, 4.17]} />
        <mesh name="Extruder_Main_-_Mold_Subassembly-1_Plastic_Mold-1001" geometry={nodes['Extruder_Main_-_Mold_Subassembly-1_Plastic_Mold-1001'].geometry} material={materials.Barrel} position={[0.81, 1.46, 4.31]} />
        <mesh name="Extruder_Main_-_Mold_Subassembly-1_Breaker_Plate-1001" geometry={nodes['Extruder_Main_-_Mold_Subassembly-1_Breaker_Plate-1001'].geometry} material={materials.Barrel} position={[0.81, 1.46, 4.18]} />
        <mesh name="Extruder_Main_-_Mold_Subassembly-1_socket_countersunk_head_004" geometry={nodes['Extruder_Main_-_Mold_Subassembly-1_socket_countersunk_head_004'].geometry} material={materials.Barrel} position={[0.81, 1.46, 4.18]} />
        <mesh name="Main_Bed" geometry={nodes.Main_Bed.geometry} material={materials.Main_Bed} position={[0.81, 1.16, 3]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Extruder.glb')
