/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Yuka(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Models/yuka.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Character" rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.Armature_Hips} />
          <skinnedMesh name="Kachujin" geometry={nodes.Kachujin.geometry} material={materials.kachujin_MAT} skeleton={nodes.Kachujin.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Models/yuka.glb')
